{
 "title": "Service overview",
 "description": "CPU, RAM etc",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  node_filesystem_avail_bytes\n  /\n  node_filesystem_size_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  node_memory_MemAvailable_bytes\n  /\n  node_memory_MemTotal_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (\n  avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}