{
 "title": "RED",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_response_status_code=\"500\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error 4XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_response_status_code=~\"404|400|401|403\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Seconds Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}