{
 "title": "KPI",
 "description": "Business metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Delete from minio per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(counter_meter_total{task_type=\"avatars_delete_total_minio\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download from minio per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(counter_meter_total{task_type=\"avatars_download_total_minio\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minio Upload Count Per Minute",
   "type": "timeseries",
   "description": "Minio Upload Count Per Minute\nBusiness metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(counter_meter_total{task_type=\"avatars_uploads_total_minio\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Event Couner Per Minute",
   "type": "timeseries",
   "description": "Business metric\nUpload Event Couner Per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(counter_meter_total{task_type=\"upload_event\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}